### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by albohlabs** [wout/svg.draggable.js#61]
@Fuzzyma please update the [npm version](https://www.npmjs.com/package/svg.draggable.js).

**Comment by Fuzzyma** [comment]
Sorry missed to publish it. 
Done!

**Comment by Rufflet** [comment]
@Fuzzyma could you please update npm version up to v2.2.1-2018-05-30

**Comment by Fuzzyma** [comment]
it is - I doublechecked, You can check it here: https://www.npmjs.com/package/svg.draggable.js

**Comment by Rufflet** [comment]
Still getting v2.2.1-**2016-08-25** instead of **2018-05-30**

I ran `npm view svg.draggable.js` and there is also v2.2.1-**2016-08-25** in [dist.tarball](https://registry.npmjs.org/svg.draggable.js/-/svg.draggable.js-2.2.1.tgz)

What am I doing wrong?

**Comment by Fuzzyma** [comment]
so you basically want a new release and not 2.2.1, right?

**Comment by Rufflet** [comment]
Oh, i didn't noticed that last release on github is also dated by _2016-08-25_. Now it's all clear for me

Sorry for bothering you ;)
